#!/bin/bash
#
#


TRSHELL_LIBS="/home/tristanstille/Projects/tristan-scripts"
source $TRSHELL_LIBS/load.sh
load.full_init $TRSHELL_LIBS

update-trshell.update


LOG_LOGLEVEL="TRACE"

log.red "RED"
log.orange "ORANGE"
log.green "GREEN"

log.trace "Command to run is: [$@]"

load.import asdf
${@}
